### PR TITLE
added some compatibility for other datatypes

### PR DESCRIPTION
**Pull request by ldb**
Added compatibility for table and number types.

### CODE REVIEW

**Comment by catwell** [comment]
Can you please explain what you are trying to achieve?

Removing the assertion is a very bad idea, if you add `nil` to the output table it will break later anyway.

Putting numbers into the table is dangerous, too, since they will be coerced to strings by `table.concat`. You may easily end up with code that is broken on Lua 5.3, for instance adding `2/1` will not have the same result in 5.1 / 5.2 and 5.3.

If you really want that, I suggest you use `tostring(a_number)` in your code. But you probably want something like `string.format("%d", a_number)` instead.

**Comment by ldb** [comment]
I commented out the assert, because every time the input was a table, it would assert there. 

I also added the `tostring(v)`

**Comment by catwell** [comment]
Sorry, maybe I wasn't clear. I said you should use `tostring(v)` or something else to convert numbers to strings _in your code_ using lua-multipart-post, not in lua-multipart-post itself.

So, replace this input:

```
{ foo = 2 }
```

by this:

```
{ foo = tostring(2) }
```

I was curious so I looked at [your code](https://github.com/cosmonawt/lua-telegram-bot/blob/57887c77361e1f75c688d8d2d4770eaa72a7f4e3/lua-bot-api.lua). I am wondering:
- Why do you put an empty string in all your `request_body` tables? It adds a an empty field called "1" to the request, it is probably not what you wanted.
- Same with fallbacks like this:

```
request_body.parse_mode = parse_mode or ""
request_body.disable_web_page_preview = disable_web_page_preview or ""
request_body.reply_to_message_id = tonumber(reply_to_message_id) or tonumber("")
request_body.reply_markup = reply_markup or ""
```

You should probably remove all the `or ""` which add empty elements to the request. And `or tonumber("")` is useless: `tonumber("")` is `nil`.
- If you really want to automatically support numbers everywhere, you can do it in your makeRequest function:

```
function makeRequest(method, request_body)

  local response = {}
  for k, v in pairs(request_body) do
    if type(v) == "number" then request_body[k] = tostring(v) end
  end
  local body, boundary = encode(request_body)

  ...
end
```

**Comment by ldb** [comment]
I added `or ""` because those fields are not mandatory. I could have either checked each of those fields presence, or add a simple fallback, which does get accepted by the server.

You are right about the `tonumber("")`, thanks for the head-up.

Also, thanks for all the hints. I will do it like that eventually.

**Comment by catwell** [comment]
About `or ""`, what I meant is that, if you just remove it, the line:

```
request_body.optional = optional or ""
```

will become

```
request_body.optional = optional
```

which, when `optional` is `nil`, puts _nothing_ in the table.

So instead of this:

```
> encode({foo = "bar", optional = ""}, "BOUNDARY")
--BOUNDARY
content-disposition: form-data; name="foo"

bar
--BOUNDARY
content-disposition: form-data; name="optional"


--BOUNDARY--
```

you will get this:

```
> encode({foo = "bar"}, "BOUNDARY")
--BOUNDARY
content-disposition: form-data; name="foo"

bar
--BOUNDARY--
```

(i.e. a request where `optional` is _really_ not set)

**Pull request closed without merging**
